### PR TITLE
Add diff and change detection to systemd generation

### LINKED ISSUE #339: Generating systemd does not affect "changed" state
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When generating the systemd file with `podman_container`, it may change the systemd file, but the task does not reflect the changed state.

**Steps to reproduce the issue:**

1. Run playbook to create container with `generate-systemd` enabled on target machine through `podman_container`

2. Delete the systemd file that got created

3. Rerun the playbook from step 1

**Describe the results you received:**
The `podman_container` task creates the systemd file and reports the output as "ok"

**Describe the results you expected:**
The `podman_container` task creates the systemd file and reports the output as "changed"

**Additional information you deem important (e.g. issue happens only occasionally):**
I didn't bother yet to reproduce this issue in an isolated fashion. If more information is needed, I can do further debugging

**Version of the `containers.podman` collection:** 1.8.1

```
1.8.1
```
I checked the recent commits since then, there seems to be no relevant commit in this direction since that release

**Output of `ansible --version`:**

```
ansible [core 2.12.0]
  config file = /home/ruben/Projects/ansible/ansible.cfg
  configured module search path = ['/home/ruben/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ruben/Projects/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.14
Built:        Thu Sep 23 23:22:19 2021
OS/Arch:      linux/amd64
```
(on target machine)

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-1.module_el8.4.0+781+acf4c33b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 76c72c12c83408e6ddaaa7bcd25e96ca20bf9348'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: status-staging
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.3.1.el8.x86_64
  linkmode: dynamic
  memFree: 1467641856
  memTotal: 3917713408
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 839h 52m 55.31s (Approximately 34.96 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 5
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 21
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1632432139
  BuiltTime: Thu Sep 23 23:22:19 2021
  GitCommit: ""
  GoVersion: go1.15.14
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-0.11.module_el8.4.0+942+d25aada8.x86_64
```

**Playbook you run with ansible (e.g. content of `playbook.yaml`):**
Only listing the relevant task here, modified for confidentiality reasons
```
- name: Create django container
  containers.podman.podman_container:
    name: webapp
    image: <redacted>
    state: present
    pod: pod
    recreate: '{{ "yes" if settings.changed else "no" }}'
    generate_systemd:
      path: "/etc/systemd/system"
  tags:
    - statuspage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos 8 VM

### PR DESCRIPTION
**Pull request by sshnaidm**
Fix #339
Signed-off-by: Sagi Shnaidman <sshnaidm@redhat.com>

### CODE REVIEW

**Comment by sshnaidm** [comment]
Need to add tests..

**Comment by nishipy** [comment]
The test will be like this?
https://github.com/containers/ansible-podman-collections/compare/master...nishipy:ansible-podman-collections:fix-339

**Comment by sshnaidm** [comment]
> The test will be like this? [nishipy@376215b](https://github.com/nishipy/ansible-podman-collections/commit/376215bc084cedbfdbe3afa07926a3ea765e7e4d)

Yeah, feel free to add it to this patch

**Comment by nishipy** [comment]
I have no permission to push your repo, so created the following PR for adding the test. Please find here:
https://github.com/sshnaidm/ansible-podman-collections/pull/10

**Pull request merged**
