### PR TITLE
podman_container should ensure image by using os path if rootfs is used

### PR DESCRIPTION
**Pull request by mainnika**
if the `rootfs` is true then podman_container should use an image argument as a path and check the existence by using os-path method. 
if there is no such a directory then the module should fire an error.

playbook example
```
- name: Container present
  containers.podman.podman_container:
    name: mycontainer
    state: present
    rootfs: yes
    image: /opt/containers/mycontainer-rootfs
    command: "sleep 1d"
```

↑ this currently fails with
```
{"changed": false, "msg": "Can't pull image /opt/containers/mycontainer-rootfs", "stderr": "Error: invalid reference format\n", "stderr_lines": ["Error: invalid reference format"], "stdout": "", "stdout_lines": []}
```

### CODE REVIEW

**Comment by sshnaidm** [comment]
As I see, the test ansible-podman-collections/tests/integration/targets/podman_container/tasks/main.yml:426 fails:
https://github.com/containers/ansible-podman-collections/blob/99c2851341999bfeb0b78458efa09f874c923a9e/tests/integration/targets/podman_container/tasks/main.yml#L419-L437

```diff
 --- before
+++ after
@@ -1 +1 @@
-label - {}
+label - None
```

**Comment by mainnika** [comment]
> As I see, the test ansible-podman-collections/tests/integration/targets/podman_container/tasks/main.yml:426 fails:
> ```diff
>  --- before
> +++ after
> @@ -1 +1 @@
> -label - {}
> +label - None
> ```

Yes, I see, changed this line back. `or` works here better than a default value.

**Comment by sshnaidm** [comment]
The failure in job is not relater, I fixed it in https://github.com/containers/ansible-podman-collections/commit/e6544bdd0a66c558e3e66caf97aae75b75720b33, so you can rebase on latest master.

**Comment by sshnaidm** [comment]
@mainnika would you like to add a test to https://github.com/containers/ansible-podman-collections/blob/master/tests/integration/targets/podman_container/tasks/main.yml ?

**Comment by sshnaidm** [comment]
check-github

**Comment by mainnika** [comment]
@sshnaidm 
Ok, will do that

**Comment by sshnaidm** [comment]
check-github

**Comment by sshnaidm** [comment]
@mainnika I can merge and you can add tests later, but I just try to keep it tested always :)

**Comment by mainnika** [comment]
I also like when everything is tested. I'll try to find a time either today or tomorrow morning.

**Comment by mainnika** [comment]
@sshnaidm
Added tests, could you please take a look, maybe I missed some cases.

**Comment by sshnaidm** [comment]
Awesome! Thanks for your great contribution!

**Pull request merged**
