### PR TITLE
Adding podman_copy with tests

### PR DESCRIPTION
**Pull request by DilasserT**
Adding a "podman_copy" module
Adding integration tests
Issue #571

### CODE REVIEW

**Comment by sshnaidm** [comment]
Thanks @DilasserT , but isn't it duplicate of [podman_container_copy](https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_container_copy.py) ?

**Comment by DilasserT** [comment]
Yes, it completely is, I'll go back to my cave.

**Comment by sshnaidm** [comment]
@DilasserT you can add things there if you have something more than implemented now. :smile:  No need to go to the cave. Also we need podman commit and probably [other modules](https://github.com/containers/ansible-podman-collections/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement), you did a great job with this one.

**Comment by DilasserT** [comment]
@sshnaidm Are you thinking about some code from this PR that might be added or something else entirely ?
I will look at other features, maybe this time I will take less than a year to implement some integration tests...

**Comment by sshnaidm** [comment]
@DilasserT probably current module covers everything `podman cp` is doing, but there are other RFEs are opened. Now you're more familiar with how to do tests, so will be easier!

**Pull request closed without merging**
