### PR TITLE
Add log_opt and annotaion options to podman_play module

### LINKED ISSUE #544: Add some genernal parameters in `containers.podman.podman_play`
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Describe the results you expected:**
add some genernal parameters in `containers.podman.podman_play` , e.g. `log_opt` and `userns`

**Version of the `containers.podman` collection: 1.10.1**

**Output of `podman version`:**

```
4.3.1
```

### PR DESCRIPTION
**Pull request by nishipy**
Fixes #544 and added test. 
In addition, this change adds tests for PR https://github.com/containers/ansible-podman-collections/pull/577, which is also related to issue #544.

### CODE REVIEW

**Comment by nishipy** [comment]
Hi @sshnaidm, the task `Install podman` in `ci/playbooks/pre.yml` failed for some reason (the log says `Failed to fetch` packages...). Could you have a look? Thank you.

**Comment by sshnaidm** [comment]
> Hi @sshnaidm, the task `Install podman` in `ci/playbooks/pre.yml` failed for some reason (the log says `Failed to fetch` packages...). Could you have a look? Thank you.

This is a problem with opensuse repositories which we use for installing a new Podman, need to wait until it's fixed. Happens quite a lot, btw.
image

**Comment by sshnaidm** [comment]
Checking here: https://status.opensuse.org/

**Comment by nishipy** [comment]
Thank you for the information.I see. Then, let me retry after it gets fixed.

**Comment by nishipy** [comment]
@sshnaidm Finally opensuse repositories have come back and all checks have passed. Please review this PR at your convenience. Thank you.

**Comment by sshnaidm** [comment]
Awesome, thanks!

**Pull request merged**
