### PR TITLE
Fix play_kube not working when yaml not installed on target (#415)

### LINKED ISSUE #415: podman_play may crash if pod with same name already exists
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using `containers.podman.podman_play`, the module may crash if a pod with the same name already exists and the `yaml` module is not available.

**Steps to reproduce the issue:**

1. Use a target machine without the `yaml` python module, eg vagrant box `debian/bullseye64`

2. Create a pod with some name on the target

3. Use `podman_play` to deploy a kubernetes file that attempts to use the same name as the pod created above and `recreate: true`

**Describe the results you received:**

Crash with `TypeError: expected string or bytes-like object`.

**Describe the results you expected:**

Pod is re-created.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**

```
containers.podman 1.9.3
```

**Output of `ansible --version`:**

```
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/home/mal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mal/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mal/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mal/.local/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.1.1
  libyaml = True
```

**Output of `podman version`:**

```
podman version 3.0.1
```

**Output of `podman info --debug`:**

``` yamlhost:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 1
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: tennant
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.0-13-amd64
  linkmode: dynamic
  memFree: 24551424
  memTotal: 496103424
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 1h 2m 9.59s (Approximately 0.04 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.15
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/stable,now 3.0.1+dfsg1-3+deb11u1 amd64 [installed]
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

Full code is [here](https://github.com/tardisproject/tardis-ansible/blob/254b5a48183e4f13a0495ff0d90e76e0fbbbc7d8/roles/monitor/tasks/main.yml#L50), invoked with `ansible --verbose tennant.local -i inventory.vagrant.yml -m include_role -a name=monitor`

``` yaml
- name: Create tempfile for pod config
  tempfile:
    state: file
  register: timeseries_tempfile

- name: Upload pod config
  template:
    src: ../files/timeseries.yml.j2
    dest: "{{ timeseries_tempfile.path }}"

- name: Deploy Prometheus+Grafana Pod
  notify: start timeseries
  containers.podman.podman_play:
    kube_file: "{{ timeseries_tempfile.path }}"
    state: created
    recreate: true
```

**Command line and output of ansible run with high verbosity**

[Here](https://gist.github.com/tcmal/1a7a29ad473f2e7691d4abf4ae6a7069)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

[Vagrantfile](https://github.com/tardisproject/tardis-ansible/blob/main/Vagrantfile) & [Inventory](https://github.com/tardisproject/tardis-ansible/blob/main/inventory.vagrant.yml)

### PR DESCRIPTION
**Pull request by tcmal**
Was passing a file handle instead of a string.

Closes #415.

### CODE REVIEW

**Comment by sshnaidm** [comment]
Please sign your commit: `git commit -s`, it's must in all repos in this org.

**Comment by sshnaidm** [comment]
check-github

**Comment by sshnaidm** [comment]
You can do `git commit -s --amend` and `git push --force` just to add the signature.

**Comment by sshnaidm** [comment]
And please rebase on latest `master`

**Comment by tcmal** [comment]
Have done.

**Comment by sshnaidm** [comment]
Thanks for your contribution!

**Pull request merged**
