### PR TITLE
Change network attribute from str to list in pods #414

### PR DESCRIPTION
**Pull request by MrSuicideParrot**
This pull request implements the suggestion mentioned in the issue #414

### CODE REVIEW

**Comment by sshnaidm** [comment]
Please sign your commit: `git commit -s`, it's must in all repos in this org.

**Comment by MrSuicideParrot** [comment]
I checked the failed tasks, and I wasn't able to understand why they failed. The network `10.90.90.0/24` is only used in one place and is created by a podman command, so I don't understand how my commit managed to break this.  Do you have any idea?

**Review by sshnaidm — CHANGES_REQUESTED** [review]
In line 495 need to change:

```diff
- if self.params['network'] == 'host':
+ if 'host' in self.params['network']:
```

**Comment by sshnaidm** [comment]
The real problem is here: https://paste.opendev.org/show/bqf4dxKPr2QcoGLgoBAS/

**Comment by sshnaidm** [comment]
Sorry, seems like I screwed it up while updating your patch. Can you resubmit maybe?

**Pull request closed without merging**
